### ISSUE TITLE
OOM in async event loop

### ISSUE THREAD

**Issue by DevinR528** [lunaryorn/mdcat#150]
I am using this to display messages for a chat app [rumatui](https://github.com/DevinR528/rumatui/) `mdcat` is working great and is probably my favorite part of the whole thing. Thanks!

After doing some upgrades, not to `mdcat` but, other deps I started getting OOM errors. What I think is happening is in a somewhat tight async loop I'm calling the `mdcat::push_tty` function this OOMS with a stack trace of bincode and serde deserialize calls.

So calling [this](https://github.com/DevinR528/rumatui/blob/OOM-fix/src/widgets/utils.rs#L37-L60) for every message event that comes in, probably at least a few 100 in an async event loop.

Any ideas on how to avoid so much allocation?

**Comment by lunaryorn** [comment]
I'm sorry but how am I supposed to help here?  I don't see what I should do here.

**Comment by lunaryorn** [comment]
@DevinR528 That said, it looks as if you [changed the code](https://github.com/DevinR528/rumatui/commit/6e1e6f22b37f690e574c491536dc934776d253d0) around the time you opened this issue; would you like me to look at the old or the new version?

As far as I can see the old version creates a new `syntect::SyntaxSet` for `mdcat::push_tty` call; please be aware that syntax sets are expensive to construct and likely allocate a lot of memory.  Factoring the `syntect:;SyntaxSet` out and constructing it only once can perhaps reduce memory pressure a lot.  I'd recommend to create the syntax set and the terminal capabilities only once for your application on startup, and pass it downwards to where you render markdown.  I'd not use `lazy_static` since it makes the first call, i.e. the first message rendered, somewhat expensive – constructing it upfront and passing it downwards gives the function more predictable performance characteristics. 

As a closing note I haven't really attempted to "optimize" mdcat nor do I intend to – for my purposes it's still a command line tool where memory efficiency is not so much of a concern.   But still I don't think that mdcat's rendering allocates an excessive amount of memory and I don't think it's to blame here.  I'm happy to be proven wrong but only by a pull request: I for my part don't intend to spend my time on this even if there was a memory issue in mdcat.

Hence I'm closing this issue.

**Comment by DevinR528** [comment]
Thanks for taking a look at it at all sorry if I was too vague before it was a bit late and I had been looking at it for a while. I wasn't making a criticism, from my investigations, and as you said `syntect` is the (justifiably) expensive one. If I make any progress I'll be sure to open a PR in case you are interested.

Thanks again!
