### ISSUE TITLE
[Feature Request] Image Caching

### ISSUE THREAD

**Issue by tddschn** [lunaryorn/mdcat#164]
Image Caching will make mdcat render the content of markdown files with Internet images much faster the second time,
so I think it might be a good idea to implement Internet images caching (in the feature). :)

**Comment by lunaryorn** [comment]
That's a nice idea, but also one that you'll need to implement yourself, because I don't need it myself and don't want to implement it myself, even less so since there's a lot of complexity behind this simple idea with regards to cache expiration, etc.

Feel free to open a pull request.

Meanwhile I close this as I prefer to keep only those issues open which I intend to work on myself at some point

**Comment by tddschn** [comment]
Thanks for the quick reply! That's understandable.

I am aware of the complexity behind this feature. This feature is nice-to-have but not necessary to me either. Guess we'll leave it closed for now. :)
