### ISSUE TITLE
Highlighting for quotes does not behave as in the example in the README

### ISSUE THREAD

**Issue by shiroyasha** [lunaryorn/mdcat#22]
Screenshot example:

![screen shot 2018-02-14 at 9 21 01 pm](https://user-images.githubusercontent.com/1779493/36226049-02dbb76a-11cd-11e8-9032-4189cae8f3dd.png)

My configuration is:

 - iTerm2 Build 3.1.5
 - 15pt Monaco font
 - Built in Pasted color scheme
 - tmux inside of a vagrant ubuntu image

**Comment by lunaryorn** [comment]
Hi, thanks for reporting this issue.  I think tmux causes this—it interprets and perhaps changes escape sequences.  Perhaps `mdcat` does something wrong, too, but I must admit that since I it works for me and I don't use tmux a lot, I don't feel like digging deeper.

I'm open for a pull request, but please understand that I don't want to fix this issue by myself.  Sorry.

**Comment by lunaryorn** [comment]
I'm closing this issue as wontfix now.
