### ISSUE TITLE
a 32 bit build?

### ISSUE THREAD

**Issue by sc0ttj** [lunaryorn/mdcat#97]
Any chance?

**Comment by lunaryorn** [comment]
I'm sorry but it's long since I've seen a 32 bit system, so personally I'd not like to spend my time on configuring a 32 bit build.

Feel free to open a pull request which adds a 32 bit build—depending on the impact I might ask to port the entire release build setup to Github actions first, though 😇 

Note that you can always build yourself: Just install rustup and `cargo install mdcat` :)
